from typing import Protocol
from uuid import UUID

from backend.models.tasks import Goal, Task, TaskGoalLink


class TaskRepository(Protocol):
    """Persistence port for user-owned tasks and their goal links."""

    async def create_task(self, task: Task) -> None: ...

    async def update_task(self, task: Task) -> None: ...

    async def get_task(self, user_id: UUID, task_id: UUID) -> Task: ...

    async def list_tasks(self, user_id: UUID, include_archived: bool) -> tuple[Task, ...]: ...

    async def list_goal_links(self, user_id: UUID) -> tuple[TaskGoalLink, ...]: ...

    async def delete_task(self, user_id: UUID, task_id: UUID) -> None: ...

    async def add_goal(self, user_id: UUID, task_id: UUID, goal_id: UUID) -> None: ...

    async def remove_goal(self, user_id: UUID, task_id: UUID, goal_id: UUID) -> None: ...

    async def list_goal_ids(self, user_id: UUID, task_id: UUID) -> tuple[UUID, ...]: ...


class GoalRepository(Protocol):
    """Persistence port for user-owned goals."""

    async def create_goal(self, goal: Goal) -> None: ...

    async def update_goal(self, goal: Goal) -> None: ...

    async def get_goal(self, user_id: UUID, goal_id: UUID) -> Goal: ...

    async def list_goals(self, user_id: UUID, include_archived: bool) -> tuple[Goal, ...]: ...

    async def delete_goal(self, user_id: UUID, goal_id: UUID) -> None: ...
